import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {
  SignInButton,
  SignIn,
  SignedOut,
  useUser,
  useClerk,
} from "@clerk/nextjs";
import { api } from "~/utils/api";
import { postsRouter } from "../server/api/routers/posts";
const Home: NextPage = () => {
  const { data } = api.example.getAll.useQuery();
  const user = useUser();
  console.log("user", user.isSignedIn);
  const { signOut } = useClerk();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Sign In</h1>
          <h1>hello</h1>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && (
            <button onClick={() => signOut()}>sign out</button>
          )}
        </div>
        <div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
